var defaultCode = [
  '// feel free to change,',
  '// just leave `return` on its place',
  '',
  'var root = element(\'root\').band(0, duration)',
  '                          .move(width / 2, height / 2);',
  '',
  'for (var i = 0; i < 20; i++) {',
  '    root.add(',
  '        element(\'r-\' + i).band(0, duration)',
  '                         .rect(10 + (Math.random() * 90))',
  '                         .fill(Color.dhsl(Math.random() * 360, 0.5, 0.5))',
  '                         .modify(',
  '                             Tween.translate()',
  '                                  .value(new Path().move(0, 0)',
  '                                                   .line((Math.random() * width)  - (width  / 2),',
  '                                                         (Math.random() * height) - (height / 2)))',
  '                                  .easing(\'out\'))',
  '    );',
  '}',
  '',
  'return root.modify(function(t) {',
  '                       this.angle = t;',
  '                   });'
].join('\n');

var examples = [];
examples.push([ 0 /*version*/, 'Rectangles' /* name */, defaultCode ]);

examples.push([ 0 /*version*/, 'Ink' /* name */, [
  'var emitter = element().move(width / 2, height / 2);',
  '',
  'for (var i = 0; i < 50; i++) {',
  '    var lifetime = Math.random() * 10;',
  '    var start = Math.random() * duration;',
  '    emitter.add(',
  '        element().band(start, start + lifetime)',
  '                 .oval(Math.random() * 30)',
  '                 .stroke(\'#000\', 2)',
  '                 .fill(\'#000\')',
  '                 .modify(Tween.translate()',
  '                              .from(0, 0)',
  '                              .to((Math.random() * width) - (width / 2),',
  '                                  (i % 2) ? (Math.random() * height) - (height / 2) : 0))',
  '    );',
  '}',
  '',
  'return emitter;'
].join('\n') ]);

examples.push([ 0 /*version*/, 'Clouds' /* name */, [
  'var sky = element(\'sky\').reg(-(width / 2), -(height / 2))',
  '                        .rect(width, height)',
  '                        .fill(Brush.gradient().stops({ 0.5: \'#effbff\', 1: \'#fff\' })',
  '                                              .size(width, height))',
  '',
  'sky.add(element(\'sun\').oval(40)',
  '                      .move(100,100)',
  '                      .fill(\'#ffec00\')',
  '                      .shadow(\'#ff0\',20));',
  '',
  'var clouds = Math.floor(Math.random() * 10) + 5; // from 5 to 15',
  'for (var cloud = 0; cloud < clouds; cloud++) {',
  '',
  '    var pietals  = Math.floor((Math.random() * 6) + 7); // from 7 to 13',
  '    var xradius  = (Math.random() * 20) + 10, yradius = xradius * 0.75,',
  '        oxradius = xradius + 10, oyradius = yradius + 10;',
  '    var path = new Path().move(xradius, 0);',
  '    var prev_t = 0, t;',
  '    for (var pietal = 1; pietal <= pietals; pietal++) {',
  '        var t = (pietal / pietals) * (2 * Math.PI);',
  '        path.curve(oxradius * Math.cos(prev_t), oyradius * Math.sin(prev_t),',
  '                   oxradius * Math.cos(t),      oyradius * Math.sin(t),',
  '                   xradius  * Math.cos(t),      yradius  * Math.sin(t));',
  '        prev_t = t;',
  '   }',
  '',
  '   var start_t = Math.random() * duration,',
  '       end_t = start_t + 4;',
  '   var start_x = -xradius, start_y = yradius + (Math.random() * 200);',
  '   sky.add(',
  '      element(\'cloud\'+cloud).band(start_t, end_t)',
  '                            .modify(Tween.translate().from(start_x, start_y)',
  '                                                     .to(width + (xradius * 2), start_y))',
  '                            .path(path) // set precalculated path',
  '                            .fill(\'#fff\')',
  '                            .shadow(\'#fff\', 10, 5, 5));',
  '}',
  '',
  'return sky;'
].join('\n') ]);

examples.push([ 0 /*version*/, 'Stars' /* name */, [
    'var root = element();',
    '',
    'root.reg(-(width / 2), -(height / 2))',
    '    .rect(width, height)',
    '    .fill(Brush.gradient().stops({ 0.2: \'#335\', 1: \'#000\' })',
    '                          .size(width, height));',
    '',
    'var rows = 17;',
    'var cols = 10;',
    '',
    'for (var r = 0; r < rows; r++) {',
    '    for (var c = 0; c < cols; c++) {',
    '        root.add(element().move(5 + (r * 25) + (Math.random() * 13),',
    '                                5 + (c * 25) + (Math.random() * 13))',
    '                          .paint(function(ctx) {',
    '                              var ends_count = Math.ceil(Math.random() * 7);',
    '                              var path = new Path();',
    '                              for (var i = 0; i < ends_count; i++) {',
    '                                  path.move(0, 0).line((Math.random() * 3) - 1.5,',
    '                                                       (Math.random() * 3) - 1.5);',
    '                              }',
    '                              path.apply(ctx,',
    '                                         null, // fill',
    '                                         Brush.stroke(\'#eed\', 2));',
    '                           })',
    '                 )',
    '    }',
    '}',
    '',
    'return root;'
].join('\n') ]);
