# Thanks to http://github.com/mark-rushakoff/OpenPhantomScripts

language: ruby
rvm:
  - 1.9.3
notifications:
  email: false
before_script:
  # Travis needs this stuff to start Phantom1.4...
  # When they get Phantom1.5 this section can go away
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "phantomjs ./tests/run-jasmine.phantom.js ./tests/run-for-terminal.html"
