/*
 * Copyright (c) 2011-2013 by Animatron.
 * All rights are reserved.
 *
 * Animatron player is licensed under the MIT License, see LICENSE.
 */

var _specs = {
   '00.testutils': null,
   '01.player': [ '01.formation',
                  '02.initializing',
                  '03.playing',
                  '04.modes',
                  '05.loading',
                  '06.errors',
                  '07.utils',
                  '08.version',
                  '09.events',
                  '10.embedding' ],
   '02.animations': [ '01.guids',
                      '02.duration-n-bands',
                      '03.structure',
                      '04.repeat-modes',
                      '05.jumps' ],
   '03.anm-import': [ '01.elements',
                      '02.bands',
                      '03.tweens',
                      '04.masks',
                      '05.layers',
                      '06.versions',
                      '07.meta',
                      '_utils.and.their' ],
   '04.builder': [ '01.formation',
                   '02.structure',
                   '03.shapes',
                   '04.fill-n-stroke',
                   '05.statics',
                   '06.duration-n-bands',
                   '07.tweens',
                   '08.repeat-modes',
                   '09a.modifiers',
                   '09b.painters',
                   '10.time-switch',
                   '11.events',
                   '12.take-n-use',
                   '13.enable-disable',
                   '14.iterations',
                   '15.detach-n-clear',
                   '16.data',
                   '17.compositing',
                   '18.masks',
                   '19.helpers',
                   '20.image' ],
   '05.collisions': [ 'stub' ],
   '06.bugs': [ 'bugs' ]
};